import { createClient } from '@supabase/supabase-js';
import { NextRequest, NextResponse } from 'next/server';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL || '',
  process.env.SUPABASE_SERVICE_ROLE_KEY || ''
);

// GET /api/v1/processing/export/markdown?project_id=xxx
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const projectId = searchParams.get('project_id');

    if (!projectId) {
      return NextResponse.json(
        { error: 'project_id is required' },
        { status: 400 }
      );
    }

    // Fetch processing activities with legal basis
    const { data: activities, error } = await supabase
      .from('processing_activities')
      .select(`
        *,
        legal_basis:legal_basis_id (*)
      `)
      .eq('project_id', projectId)
      .is('deleted_at', null)
      .eq('is_active', true)
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error fetching processing activities:', error);
      return NextResponse.json(
        { error: 'Failed to fetch processing activities' },
        { status: 500 }
      );
    }

    if (!activities || activities.length === 0) {
      return NextResponse.json(
        { error: 'No processing activities found' },
        { status: 404 }
      );
    }

    // Generate markdown content
    const generationDate = new Date().toISOString().split('T')[0];
    let markdown = `# GDPR Article 30 Record of Processing Activities\n\n`;
    markdown += `**Project ID:** ${projectId}\n\n`;
    markdown += `**Generated:** ${generationDate}\n\n`;
    markdown += `**Total Activities:** ${activities.length}\n\n`;
    markdown += `---\n\n`;

    activities.forEach((activity: any, index: number) => {
      markdown += `## ${index + 1}. ${activity.name}\n\n`;
      
      // Purpose
      markdown += `### Purpose\n\n`;
      markdown += `${activity.purpose}\n\n`;
      
      // Legal Basis
      markdown += `### Legal Basis\n\n`;
      if (activity.legal_basis) {
        const lb = activity.legal_basis;
        const typeLabels: Record<string, string> = {
          consent: 'Consent (Art. 6.1a)',
          contract: 'Contract (Art. 6.1b)',
          legal_obligation: 'Legal Obligation (Art. 6.1c)',
          vital_interests: 'Vital Interests (Art. 6.1d)',
          public_task: 'Public Task (Art. 6.1e)',
          legitimate_interest: 'Legitimate Interest (Art. 6.1f)',
        };
        markdown += `- **Type:** ${typeLabels[lb.basis_type] || lb.basis_type}\n`;
        markdown += `- **Name:** ${lb.name}\n`;
        if (lb.description) {
          markdown += `- **Description:** ${lb.description}\n`;
        }
        if (lb.basis_type === 'legitimate_interest' && lb.legitimate_interest_reason) {
          markdown += `- **LIA:** ${lb.legitimate_interest_reason}\n`;
        }
      }
      markdown += `\n`;
      
      // Data Categories
      if (activity.data_categories && activity.data_categories.length > 0) {
        markdown += `### Data Categories\n\n`;
        activity.data_categories.forEach((cat: string) => {
          markdown += `- ${cat}\n`;
        });
        markdown += `\n`;
      }
      
      // Retention
      if (activity.data_retention_days) {
        markdown += `### Retention Period\n\n`;
        markdown += `${activity.data_retention_days} days\n\n`;
      }
      
      // Recipients
      if (activity.recipients) {
        markdown += `### Data Recipients\n\n`;
        markdown += `${activity.recipients}\n\n`;
      }
      
      // Safeguards
      if (activity.safeguards) {
        markdown += `### Security Measures\n\n`;
        markdown += `${activity.safeguards}\n\n`;
      }
      
      // Metadata
      markdown += `### Metadata\n\n`;
      markdown += `- **Created:** ${new Date(activity.created_at).toISOString()}\n`;
      markdown += `- **Updated:** ${new Date(activity.updated_at).toISOString()}\n\n`;
      
      markdown += `---\n\n`;
    });
    
    markdown += `## Summary\n\n`;
    markdown += `This document contains **${activities.length}** processing activities.\n\n`;
    markdown += `Generated by AgentTrace GDPR Compliance System\n`;

    // Return markdown with proper headers
    return new NextResponse(markdown, {
      status: 200,
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        'Content-Disposition': `attachment; filename="gdpr_ropa_${projectId}_${new Date().toISOString().split('T')[0]}.md"`,
        'Cache-Control': 'no-cache',
      },
    });
  } catch (error) {
    console.error('Error in GET /api/v1/processing/export/markdown:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
