"""P&L Reporting System.

Provides automated daily and weekly P&L reports with 
customizable scheduling and delivery.
"""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum, auto
from typing import Dict, List, Optional, Any, Callable
from pathlib import Path

import json

from ..ml.database import MLDatabase
from .alerts import AlertManager, AlertSeverity
from .metrics import MetricsCollector, PerformanceMetrics

logger = logging.getLogger(__name__)


class ReportSchedule(Enum):
    """Report schedule options."""
    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"


@dataclass
class PnLReport:
    """Profit and Loss report."""
    report_id: str
    report_type: ReportSchedule
    start_date: datetime
    end_date: datetime
    metrics: PerformanceMetrics
    insights: List[str] = field(default_factory=list)
    
    # Additional stats
    best_performing_strategy: Optional[str] = None
    worst_performing_strategy: Optional[str] = None
    total_win_rate: float = 0.0
    average_trade_pnl: float = 0.0
    
    generated_at: datetime = field(default_factory=datetime.now)
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'report_id': self.report_id,
            'report_type': self.report_type.value,
            'start_date': self.start_date.isoformat(),
            'end_date': self.end_date.isoformat(),
            'metrics': self.metrics.to_dict() if self.metrics else {},
            'insights': self.insights,
            'best_performing_strategy': self.best_performing_strategy,
            'worst_performing_strategy': self.worst_performing_strategy,
            'total_win_rate': self.total_win_rate,
            'average_trade_pnl': self.average_trade_pnl,
            'generated_at': self.generated_at.isoformat(),
        }
    
    def to_markdown(self) -> str:
        """Convert to Markdown format."""
        lines = [
            f"# P&L Report: {self.report_type.value.capitalize()}",
            f"**Period:** {self.start_date.strftime('%Y-%m-%d')} to {self.end_date.strftime('%Y-%m-%d')}",
            f"**Generated:** {self.generated_at.strftime('%Y-%m-%d %H:%M')}",
            "",
            "## Summary",
            f"- **Total Trades:** {self.metrics.total_trades if self.metrics else 0}",
            f"- **Total P&L:** ${self.metrics.total_pnl:+.2f if self.metrics else 0}",
            f"- **Win Rate:** {self.total_win_rate:.1%}",
            f"- **Average Trade P&L:** ${self.average_trade_pnl:+.2f}",
            "",
            "## Strategy Performance",
        ]
        
        if self.metrics and self.metrics.strategies:
            for stype, strat in self.metrics.strategies.items():
                lines.extend([
                    f"### {stype.capitalize()}",
                    f"- Trades: {strat.total_trades} ({strat.winning_trades}W / {strat.losing_trades}L)",
                    f"- Win Rate: {strat.win_rate:.1%}",
                    f"- Total P&L: ${strat.total_pnl:+.2f}",
                    f"- Avg Win: ${strat.avg_win:+.2f}",
                    f"- Avg Loss: ${strat.avg_loss:+.2f}",
                    "",
                ])
        
        lines.extend([
            "## Insights",
        ])
        
        for insight in self.insights:
            lines.append(f"- {insight}")
        
        lines.extend([
            "",
            "---",
            "*Generated by Kalshi Trader ML Pipeline*",
        ])
        
        return "\n".join(lines)


class PnLReporter:
    """P&L reporting system.
    
    Generates automated daily and weekly reports with configurable
    scheduling and delivery options.
    
    Parameters
    ----------
    db : MLDatabase
        Database for trade data
    alert_manager : AlertManager | None
        Alert manager for notifications
    metrics_collector : MetricsCollector | None
        Metrics collector instance
    reports_path : str
        Path to save reports
    
    Example
    -------
    >>> from kalshi_trader.monitoring import PnLReporter, ReportSchedule
    >>> 
    >>> reporter = PnLReporter(db)
    >>> reporter.add_schedule(ReportSchedule.DAILY, time="17:00")
    >>> await reporter.start()
    """
    
    def __init__(
        self,
        db: MLDatabase,
        alert_manager: Optional[AlertManager] = None,
        metrics_collector: Optional[MetricsCollector] = None,
        reports_path: str = "reports",
    ):
        self.db = db
        self.alert_manager = alert_manager
        self.metrics_collector = metrics_collector
        self.reports_path = Path(reports_path)
        self.reports_path.mkdir(parents=True, exist_ok=True)
        
        self._schedules: Dict[ReportSchedule, Dict[str, Any]] = {}
        self._custom_schedules: List[Dict[str, Any]] = []
        self._running = False
        self._task: Optional[asyncio.Task] = None
        
        self._report_history: List[PnLReport] = []
        self._max_history = 30
    
    def add_schedule(
        self,
        schedule: ReportSchedule,
        time: str = "17:00",
        day_of_week: Optional[int] = None,  # 0=Monday for weekly
        day_of_month: Optional[int] = None,  # 1-31 for monthly
        enabled: bool = True,
    ) -> None:
        """Add a report schedule.
        
        Parameters
        ----------
        schedule : ReportSchedule
            Schedule type
        time : str
            Time to send (HH:MM format)
        day_of_week : int | None
            For weekly reports: 0=Monday, 6=Sunday
        day_of_month : int | None
            For monthly reports: 1-31
        enabled : bool
            Whether schedule is active
        """
        from datetime import time as dt_time
        
        hour, minute = map(int, time.split(':'))
        
        self._schedules[schedule] = {
            'time': dt_time(hour, minute),
            'day_of_week': day_of_week,
            'day_of_month': day_of_month,
            'enabled': enabled,
        }
        
        logger.info(f"Added {schedule.value} report schedule at {time}")
    
    def generate_report(
        self,
        report_type: ReportSchedule,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None,
    ) -> PnLReport:
        """Generate a P&L report.
        
        Parameters
        ----------
        report_type : ReportSchedule
            Type of report
        start_date : datetime | None
            Report start date
        end_date : datetime | None
            Report end date
            
        Returns
        -------
        PnLReport
            Generated report
        """
        # Determine date range
        if end_date is None:
            end_date = datetime.now()
        
        if start_date is None:
            if report_type == ReportSchedule.DAILY:
                start_date = end_date - timedelta(days=1)
            elif report_type == ReportSchedule.WEEKLY:
                start_date = end_date - timedelta(weeks=1)
            elif report_type == ReportSchedule.MONTHLY:
                start_date = end_date - timedelta(days=30)
            else:
                start_date = end_date - timedelta(days=1)
        
        # Get metrics for period
        if self.metrics_collector:
            # Filter metrics by date range
            recent_trades = self.metrics_collector.get_recent_trades(n=10000)
            period_trades = [
                t for t in recent_trades
                if start_date <= t.timestamp <= end_date
            ]
            
            # Calculate metrics
            total_trades = len(period_trades)
            total_pnl = sum(t.pnl for t in period_trades)
            
            metrics = PerformanceMetrics(
                total_trades=total_trades,
                total_pnl=total_pnl,
            )
            
            # Strategy breakdown
            strategy_pnl: Dict[str, float] = {}
            for t in period_trades:
                if t.suggestion_type not in strategy_pnl:
                    strategy_pnl[t.suggestion_type] = 0.0
                strategy_pnl[t.suggestion_type] += t.pnl
            
            best_strategy = max(strategy_pnl.items(), key=lambda x: x[1])[0] if strategy_pnl else None
            worst_strategy = min(strategy_pnl.items(), key=lambda x: x[1])[0] if strategy_pnl else None
            
            win_rate = sum(1 for t in period_trades if t.outcome) / total_trades if total_trades > 0 else 0.0
            avg_pnl = total_pnl / total_trades if total_trades > 0 else 0.0
            
        else:
            metrics = PerformanceMetrics()
            best_strategy = None
            worst_strategy = None
            win_rate = 0.0
            avg_pnl = 0.0
        
        # Generate insights
        insights = self._generate_insights(metrics, report_type)
        
        report = PnLReport(
            report_id=f"{report_type.value}_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
            report_type=report_type,
            start_date=start_date,
            end_date=end_date,
            metrics=metrics,
            insights=insights,
            best_performing_strategy=best_strategy,
            worst_performing_strategy=worst_strategy,
            total_win_rate=win_rate,
            average_trade_pnl=avg_pnl,
        )
        
        # Save report
        self._save_report(report)
        
        # Send notification
        if self.alert_manager:
            self._send_report_alert(report)
        
        # Add to history
        self._report_history.append(report)
        if len(self._report_history) > self._max_history:
            self._report_history = self._report_history[-self._max_history:]
        
        return report
    
    def generate_daily_report(self, date: Optional[datetime] = None) -> PnLReport:
        """Generate daily report."""
        if date is None:
            date = datetime.now()
        
        start = date.replace(hour=0, minute=0, second=0, microsecond=0)
        end = start + timedelta(days=1)
        
        return self.generate_report(ReportSchedule.DAILY, start, end)
    
    def generate_weekly_report(self, end_date: Optional[datetime] = None) -> PnLReport:
        """Generate weekly report."""
        if end_date is None:
            end_date = datetime.now()
        
        start = end_date - timedelta(weeks=1)
        
        return self.generate_report(ReportSchedule.WEEKLY, start, end_date)
    
    def _generate_insights(
        self,
        metrics: PerformanceMetrics,
        report_type: ReportSchedule,
    ) -> List[str]:
        """Generate insights from metrics."""
        insights = []
        
        if not metrics or metrics.total_trades == 0:
            insights.append("No trading activity in this period.")
            return insights
        
        # P&L insight
        if metrics.total_pnl > 0:
            insights.append(f"Profitable period with ${metrics.total_pnl:+.2f} total P&L")
        else:
            insights.append(f"Unprofitable period with ${metrics.total_pnl:+.2f} total P&L")
        
        # Win rate insight
        if hasattr(metrics, 'total_win_rate') and metrics.total_win_rate:
            rate = metrics.total_win_rate
            if rate >= 0.6:
                insights.append(f"Excellent win rate of {rate:.1%}")
            elif rate >= 0.5:
                insights.append(f"Good win rate of {rate:.1%}")
            else:
                insights.append(f"Below-average win rate of {rate:.1%}, consider reviewing strategies")
        
        # Strategy insights
        if metrics.strategies:
            best = max(metrics.strategies.items(), key=lambda x: x[1].total_pnl)
            worst = min(metrics.strategies.items(), key=lambda x: x[1].total_pnl)
            
            if best[1].total_pnl > 0:
                insights.append(f"Best performing: {best[0].capitalize()} with ${best[1].total_pnl:+.2f}")
            
            if worst[1].total_pnl < 0:
                insights.append(f"Underperforming: {worst[0].capitalize()} with ${worst[1].total_pnl:+.2f}")
        
        # Circuit breaker insight
        if metrics.circuit_breakers_triggered > 0:
            insights.append(f"Circuit breaker triggered {metrics.circuit_breakers_triggered} times")
        
        return insights
    
    def _save_report(self, report: PnLReport) -> None:
        """Save report to file."""
        filename = f"{report.report_id}.json"
        filepath = self.reports_path / filename
        
        try:
            filepath.write_text(json.dumps(report.to_dict(), indent=2))
            logger.info(f"Report saved to {filepath}")
        except Exception as e:
            logger.error(f"Failed to save report: {e}")
    
    def _send_report_alert(self, report: PnLReport) -> None:
        """Send report as alert."""
        if not self.alert_manager:
            return
        
        self.alert_manager.send_daily_pnl_report(
            daily_pnl=report.metrics.total_pnl if report.metrics else 0,
            total_trades=report.metrics.total_trades if report.metrics else 0,
            win_rate=report.total_win_rate,
            cumulative_pnl=report.metrics.total_pnl if report.metrics else 0,
        )
    
    async def start(self) -> None:
        """Start scheduled reporting."""
        if self._running:
            return
        
        self._running = True
        
        while self._running:
            try:
                await self._check_schedules()
                await asyncio.sleep(60)  # Check every minute
            except Exception as e:
                logger.error(f"Reporting error: {e}")
                await asyncio.sleep(60)
    
    def stop(self) -> None:
        """Stop scheduled reporting."""
        self._running = False
        if self._task:
            self._task.cancel()
    
    async def _check_schedules(self) -> None:
        """Check if any reports need to be generated."""
        now = datetime.now()
        
        for schedule, config in self._schedules.items():
            if not config['enabled']:
                continue
            
            scheduled_time = config['time']
            
            # Check if it's time for this report
            should_run = False
            
            if schedule == ReportSchedule.DAILY:
                should_run = (now.hour == scheduled_time.hour and 
                            now.minute == scheduled_time.minute)
            
            elif schedule == ReportSchedule.WEEKLY:
                day_of_week = config.get('day_of_week', 6)  # Default to Sunday
                should_run = (now.weekday() == day_of_week and
                            now.hour == scheduled_time.hour and
                            now.minute == scheduled_time.minute)
            
            elif schedule == ReportSchedule.MONTHLY:
                day_of_month = config.get('day_of_month', 1)  # Default to 1st
                should_run = (now.day == day_of_month and
                            now.hour == scheduled_time.hour and
                            now.minute == scheduled_time.minute)
            
            if should_run:
                logger.info(f"Generating scheduled {schedule.value} report")
                self.generate_report(schedule)
    
    def get_report_history(self) -> List[PnLReport]:
        """Get report history."""
        return self._report_history
    
    def export_report(self, report_id: str, format: str = "json") -> Optional[str]:
        """Export a specific report.
        
        Parameters
        ----------
        report_id : str
            Report ID
        format : str
            Export format (json, markdown)
            
        Returns
        -------
        str | None
            Exported report content
        """
        # Check in memory first
        for report in self._report_history:
            if report.report_id == report_id:
                if format == "json":
                    return json.dumps(report.to_dict(), indent=2)
                elif format == "markdown":
                    return report.to_markdown()
                else:
                    return None
        
        # Check file
        filepath = self.reports_path / f"{report_id}.json"
        if filepath.exists():
            content = filepath.read_text()
            
            if format == "json":
                return content
            elif format == "markdown":
                data = json.loads(content)
                report = PnLReport.from_dict(data) if hasattr(PnLReport, 'from_dict') else PnLReport(**data)
                return report.to_markdown() if hasattr(report, 'to_markdown') else content
        
        return None
