"""Initial migration - create base tables.

Revision ID: 001
Revises: 
Create Date: 2026-03-28

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create users table
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), default=True),
        sa.Column("is_admin", sa.Boolean(), default=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=True),
        sa.Column("subscription_tier", sa.String(length=50), default="free"),
        sa.Column("subscription_status", sa.String(length=50), default="inactive"),
        sa.Column("monthly_sessions_used", sa.Integer(), default=0),
        sa.Column("monthly_sessions_limit", sa.Integer(), default=100),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    
    # Create sessions table
    op.create_table(
        "sessions",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), default="recording"),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("storage_backend", sa.String(length=50), default="local"),
        sa.Column("storage_key", sa.String(length=512), nullable=True),
        sa.Column("data_size_mb", sa.Float(), nullable=True),
        sa.Column("estimated_cost_usd", sa.Float(), default=0.0),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("parsed", sa.Boolean(), default=False),
        sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("labels", postgresql.JSON(astext_type=sa.Text()), default=list),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sessions_user_id_created", "sessions", ["user_id", "created_at"])
    op.create_index("ix_sessions_external_id", "sessions", ["external_id"], unique=True)
    op.create_index("ix_sessions_status", "sessions", ["status"])
    
    # Create session_events table
    op.create_table(
        "session_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("session_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("event_subtype", sa.String(length=100), nullable=True),
        sa.Column("timestamp_ms", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSON(astext_type=sa.Text()), default=dict),
        sa.Column("x", sa.Float(), nullable=True),
        sa.Column("y", sa.Float(), nullable=True),
        sa.Column("selector", sa.String(length=500), nullable=True),
        sa.Column("llm_reasoning", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_events_session_timestamp", "session_events", ["session_id", "timestamp_ms"])
    op.create_index("ix_events_type", "session_events", ["event_type"])
    
    # Create session_shares table
    op.create_table(
        "session_shares",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("session_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("share_token", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), default=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("view_count", sa.Integer(), default=0),
        sa.Column("last_viewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_shares_token", "session_shares", ["share_token"], unique=True)
    
    # Create api_tokens table
    op.create_table(
        "api_tokens",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), default=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_api_tokens_hash", "api_tokens", ["token_hash"], unique=True)
    
    # Create health_check_logs table
    op.create_table(
        "health_check_logs",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("check_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("db_response_ms", sa.Float(), nullable=True),
        sa.Column("storage_response_ms", sa.Float(), nullable=True),
        sa.Column("db_healthy", sa.Boolean(), default=False),
        sa.Column("storage_healthy", sa.Boolean(), default=False),
        sa.Column("overall_healthy", sa.Boolean(), default=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_health_overall", "health_check_logs", ["overall_healthy", "created_at"])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_health_overall", table_name="health_check_logs")
    op.drop_table("health_check_logs")
    
    op.drop_index("ix_api_tokens_hash", table_name="api_tokens")
    op.drop_table("api_tokens")
    
    op.drop_index("ix_shares_token", table_name="session_shares")
    op.drop_table("session_shares")
    
    op.drop_index("ix_events_type", table_name="session_events")
    op.drop_index("ix_events_session_timestamp", table_name="session_events")
    op.drop_table("session_events")
    
    op.drop_index("ix_sessions_status", table_name="sessions")
    op.drop_index("ix_sessions_external_id", table_name="sessions")
    op.drop_index("ix_sessions_user_id_created", table_name="sessions")
    op.drop_table("sessions")
    
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###